const fs = require('fs');
const path = require('path');

const RAW_SEGURANCA_92 = [
  {
    codigo: 'SG-ALMOF-00001-00',
    descricao: 'ALMOFADA P/PROT AURIC 3M/1437AE',
    descricaoExtra: '',
    materialSubGroup: 'Standard Mechanical',
    classification: 'Hydraulics & Pneumatics (valves, pistons,...)',
    subcategoria: 'Protetores Auriculares e Acessórios',
    fabricante: '3M',
  },
  {
    codigo: 'SG-ALMOF-00002-00',
    descricao: 'ALMOFADA CJ P/PROT AURIC 3M/0977',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Others',
    subcategoria: 'Protetores Auriculares e Acessórios',
    fabricante: '3M',
  },
  {
    codigo: 'SG-ALMOF-00003-00',
    descricao: 'ALMOFADA P/PROT AURIC CONCHA HONEYWELL/VS120N',
    descricaoExtra: 'KIT HIGIENE ABAFADOR FAB.HONEWELL REF.VS120N',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Others',
    subcategoria: 'Protetores Auriculares e Acessórios',
    fabricante: 'HONEYWELL',
  },
  {
    codigo: 'SG-BOTAS-00001-00',
    descricao: 'BOTA EN1007 BICO ACO PRETA C.A.28139 N 38 MARC EST',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '28139',
  },
  {
    codigo: 'SG-BOTAS-00002-00',
    descricao: 'BOTA EN1007 BICO ACO PRETA C.A. 28139 N 39 MARC ES',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '28139',
  },
  {
    codigo: 'SG-BOTAS-00003-00',
    descricao: 'BOTA EN1007 BICO ACO PRETA C.A. 28139 N 40 MARC ES',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '28139',
  },
  {
    codigo: 'SG-BOTAS-00004-00',
    descricao: 'BOTA EN1007 BICO ACO PRETA C.A. 28139 N 41 MARC ES',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '28139',
  },
  {
    codigo: 'SG-BOTAS-00005-00',
    descricao: 'BOTA EN1007 BICO ACO PRETA C.A. 28139 N 42 MARCA ES',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '28139',
  },
  {
    codigo: 'SG-BOTAS-00006-00',
    descricao: 'BOTA EN1007 BICO ACO PRETA C.A. 28139 N 34 ESTIVAL',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '28139',
  },
  {
    codigo: 'SG-BOTAS-00007-00',
    descricao: 'BOTA EN1007 BICO D ACO PRETA C.A. 28139 N 35 ESTIV',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '28139',
  },
  {
    codigo: 'SG-BOTAS-00008-00',
    descricao: 'BOTA EN1007 BICO DE ACO PRETA C.A. 28139 N36 ESTIV',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '28139',
  },
  {
    codigo: 'SG-BOTAS-00009-00',
    descricao: 'BOTA EN1007 BICO DE ACO PRETA C.A. 28139 N37 ESTIV',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '28139',
  },
  {
    codigo: 'SG-BOTAS-00010-00',
    descricao: 'BOTINA MARROM CAFE COUR CURT CA 27300 TAM 40',
    descricaoExtra: 'BICO COMPOSITE FABRICANTE BRACOL',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'BRACOL',
    ca: '27300',
  },
  {
    codigo: 'SG-BOTAS-00011-00',
    descricao: 'BOTINA MARROM CAFE COUR CURT CA 27300 TAM 41',
    descricaoExtra: 'BICO COMPOSITE FABRICANTE BRACOL',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'BRACOL',
    ca: '27300',
  },
  {
    codigo: 'SG-BOTAS-00012-00',
    descricao: 'BOTINA MARROM CAFE COUR CURT CA 27300 BICPVC BRACO',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'BRACOL',
    ca: '27300',
  },
  {
    codigo: 'SG-BOTAS-00013-00',
    descricao: 'BOTINA MARROM CAFE COUR CURT CA 27300 BICPVC BRACO',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'BRACOL',
    ca: '27300',
  },
  {
    codigo: 'SG-BOTAS-00014-00',
    descricao: 'BOTA WO20003SI BICO DE COMPOSITE CA 42553 NUM 42',
    descricaoExtra: 'BOTA ESTIVAL COR MARROM',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '42553',
  },
  {
    codigo: 'SG-BOTAS-00015-00',
    descricao: 'BOTA WO20002SI BIC ACO CA44586 NUM 42 GRAFITE ESTI',
    descricaoExtra: 'BOTA ESTIVAL COR GRAFITE',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '44586',
  },
  {
    codigo: 'SG-BOTAS-00016-00',
    descricao: 'BOTA WO20003SI BICO DE COMPOSITE CA 42553 NUM 34',
    descricaoExtra: 'BOTA ESTIVAL COR MARROM',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '42553',
  },
  {
    codigo: 'SG-BOTAS-00017-00',
    descricao: 'BOTA WO20003SI BICO DE COMPOSITE CA 42553 NUM 35',
    descricaoExtra: 'BOTA ESTIVAL COR MARROM',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '42553',
  },
  {
    codigo: 'SG-BOTAS-00018-00',
    descricao: 'BOTA WO20003SI BICO DE COMPOSITE CA 42553 NUM 36',
    descricaoExtra: 'BOTA ESTIVAL COR MARROM',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '42553',
  },
  {
    codigo: 'SG-BOTAS-00019-00',
    descricao: 'BOTA WO20003SI BICO DE COMPOSITE CA 42553 NUM 37',
    descricaoExtra: 'BOTA ESTIVAL COR MARROM',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '42553',
  },
  {
    codigo: 'SG-BOTAS-00020-00',
    descricao: 'BOTA WO20003SI BICO DE COMPOSITE CA 42553 NUM 38',
    descricaoExtra: 'BOTA ESTIVAL COR MARROM',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '42553',
  },
  {
    codigo: 'SG-BOTAS-00021-00',
    descricao: 'BOTA WO20003SI BICO DE COMPOSITE CA 42553 NUM 39',
    descricaoExtra: 'BOTA ESTIVAL COR MARROM',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '42553',
  },
  {
    codigo: 'SG-BOTAS-00022-00',
    descricao: 'BOTA WO20003SI BICO DE COMPOSITE CA 42553 NUM 40',
    descricaoExtra: 'BOTA ESTIVAL COR MARROM',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '42553',
  },
  {
    codigo: 'SG-BOTAS-00023-00',
    descricao: 'BOTA WO20003SI BICO DE COMPOSITE CA 42553 NUM 41',
    descricaoExtra: 'BOTA ESTIVAL COR MARROM',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '42553',
  },
  {
    codigo: 'SG-BOTAS-00024-00',
    descricao: 'BOTA WO20003SI BICO DE COMPOSITE CA 42553 NUM 43',
    descricaoExtra: 'BOTA ESTIVAL COR MARROM',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '42553',
  },
  {
    codigo: 'SG-BOTAS-00025-00',
    descricao: 'BOTA WO20003SI BICO DE COMPOSITE CA 42553 NUM 44',
    descricaoExtra: 'BOTA ESTIVAL COR MARROM',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '42553',
  },
  {
    codigo: 'SG-BOTAS-00026-00',
    descricao: 'BOTINA SEGURANCA C.A. 38753 BIC. COMPOSITE N.38',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    ca: '38753',
  },
  {
    codigo: 'SG-BOTAS-00027-00',
    descricao: 'BOTINA SEGURANCA C.A. 38753 BIC. COMPOSITE N.39',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    ca: '38753',
  },
  {
    codigo: 'SG-BOTAS-00028-00',
    descricao: 'SAPATO SEG HYBRID MOVE BROWN CA47750 N.39 ESTIVAL',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '47750',
  },
  {
    codigo: 'SG-CARTU-00001-00',
    descricao: 'CARTUCHO P/ MASC RESP MSA/218221',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Others',
    subcategoria: 'Proteção Respiratória',
    fabricante: 'MSA',
  },
  {
    codigo: 'SG-CINTA-00001-00',
    descricao: 'CINTA ERGONOMICA PRETA "GG" - MAZOTA',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Personal Protection Equipment',
    subcategoria: 'Ergonomia e Cintas de Proteção',
    fabricante: 'MAZOTA',
  },
  {
    codigo: 'SG-CINTA-00002-00',
    descricao: 'CINTA ERGONOMICA PRETA "G" - MAZOTA',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Personal Protection Equipment',
    subcategoria: 'Ergonomia e Cintas de Proteção',
    fabricante: 'MAZOTA',
  },
  {
    codigo: 'SG-CINTA-00003-00',
    descricao: 'CINTA ERGONOMICA PRETA "M" - MAZOTA',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Personal Protection Equipment',
    subcategoria: 'Ergonomia e Cintas de Proteção',
    fabricante: 'MAZOTA',
  },
  {
    codigo: 'SG-COLET-00001-00',
    descricao: 'COLETE SEGURANCA REFLETIVO COR: AMAR / LARAN TAM. P',
    descricaoExtra: 'COM 4 BOLSO FAB. STEELFLEX / REFLEX TIPO DE',
    materialSubGroup: 'Safety and Fire Protection',
    classification: 'Safety and Fire Protection',
    subcategoria: 'Vestimentas e Coletes Refletivos',
    fabricante: 'STEELFLEX',
  },
  {
    codigo: 'SG-COLET-00002-00',
    descricao: 'COLETE SEGURANCA REFLETIVO COR: AMAR / LARAN TAM. M',
    descricaoExtra: 'COM 4 BOLSO FAB. STEELFLEX / REFLEX TIPO DE',
    materialSubGroup: 'Safety and Fire Protection',
    classification: 'Safety and Fire Protection',
    subcategoria: 'Vestimentas e Coletes Refletivos',
    fabricante: 'STEELFLEX',
  },
  {
    codigo: 'SG-COLET-00003-00',
    descricao: 'COLETE SEGURANCA REFLETIVO COR: AMAR / LARAN TAM. G',
    descricaoExtra: 'COM 4 BOLSO FAB. STEELFLEX / REFLEX TIPO DE',
    materialSubGroup: 'Safety and Fire Protection',
    classification: 'Safety and Fire Protection',
    subcategoria: 'Vestimentas e Coletes Refletivos',
    fabricante: 'STEELFLEX',
  },
  {
    codigo: 'SG-COLET-00004-00',
    descricao: 'COLETE TACTEL AZUL ROYAL REFLETIVO T M FAB:FORTMIX',
    descricaoExtra: '',
    materialSubGroup: 'Safety and Fire Protection',
    classification: 'Safety and Fire Protection',
    subcategoria: 'Vestimentas e Coletes Refletivos',
    fabricante: 'FORTMIX',
  },
  {
    codigo: 'SG-COLET-00005-00',
    descricao: 'COLETE TACTEL AZUL ROYAL REFLETIVO T G FAB:FORTMIX',
    descricaoExtra: '',
    materialSubGroup: 'Safety and Fire Protection',
    classification: 'Safety and Fire Protection',
    subcategoria: 'Vestimentas e Coletes Refletivos',
    fabricante: 'FORTMIX',
  },
  {
    codigo: 'SG-COLET-00006-00',
    descricao: 'COLETE TACTEL AZUL ROYAL REFLETIVO TGG FAB:FORTMIX',
    descricaoExtra: '',
    materialSubGroup: 'Safety and Fire Protection',
    classification: 'Safety and Fire Protection',
    subcategoria: 'Vestimentas e Coletes Refletivos',
    fabricante: 'FORTMIX',
  },
  {
    codigo: 'SG-CREME-00001-00',
    descricao: 'CREME PROT SOL J E J/SUNDOWNFPS50120ML',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Others',
    subcategoria: 'Cremes Protetores e Higiene',
    fabricante: 'JOHNSON & JOHNSON',
  },
  {
    codigo: 'SG-CREME-00002-00',
    descricao: 'CREME II LUVEX/LUVEXINDUSTRIALPOTE200G',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Others',
    subcategoria: 'Cremes Protetores e Higiene',
    fabricante: 'LUVEX',
  },
  {
    codigo: 'SG-FITAS-00001-00',
    descricao: 'FITA DEMARC PISO AM PVC 110MM 30M',
    descricaoExtra: '',
    materialSubGroup: 'Consumables',
    classification: 'Consumables',
    subcategoria: 'Sinalização e Fitas de Demarcação',
    dimensao: '110MM X 30M',
  },
  {
    codigo: 'SG-FITAS-00002-00',
    descricao: 'FITA DEMARC PISO AM PVC 50MM 30M',
    descricaoExtra: '',
    materialSubGroup: 'Consumables',
    classification: 'Consumables',
    subcategoria: 'Sinalização e Fitas de Demarcação',
    dimensao: '50MM X 30M',
  },
  {
    codigo: 'SG-FITAS-00003-00',
    descricao: 'FITA DEMARC PISO VM PVC 100MM 30M',
    descricaoExtra: '',
    materialSubGroup: 'Consumables',
    classification: 'Consumables',
    subcategoria: 'Sinalização e Fitas de Demarcação',
    dimensao: '100MM X 30M',
  },
  {
    codigo: 'SG-FITAS-00004-00',
    descricao: 'FITA DEMARC SOLO ADES AM/PT PE 100MM 30M',
    descricaoExtra: '',
    materialSubGroup: 'Adhesives and tapes',
    classification: 'Adhesives and tapes',
    subcategoria: 'Sinalização e Fitas de Demarcação',
    dimensao: '100MM X 30M',
  },
  {
    codigo: 'SG-FITAS-00005-00',
    descricao: 'FITA DEMARC AREA AM/PT PE 70MM 200M',
    descricaoExtra: '',
    materialSubGroup: 'Consumables',
    classification: 'Consumables',
    subcategoria: 'Sinalização e Fitas de Demarcação',
    dimensao: '70MM X 200M',
  },
  {
    codigo: 'SG-LUVAS-00001-00',
    descricao: 'LUVA SEG LAT LJ G SANRO/SANROPLUSTAMG',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Luvas de Proteção e Segurança',
    fabricante: 'SANRO',
  },
  {
    codigo: 'SG-LUVAS-00002-00',
    descricao: 'LUVA SEG LAT LJ M SANRO/SANROPLUSTAMM',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Luvas de Proteção e Segurança',
    fabricante: 'SANRO',
  },
  {
    codigo: 'SG-LUVAS-00003-00',
    descricao: 'LUVA SEG RASP AM UNIC JGB/2003ARA C.A. 28650',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Luvas de Proteção e Segurança',
    fabricante: 'JGB',
    ca: '28650',
  },
  {
    codigo: 'SG-LUVAS-00004-00',
    descricao: 'LUVA SEG MALH ALG BR UNIC BUNZL/582I',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Luvas de Proteção e Segurança',
    fabricante: 'BUNZL',
  },
  {
    codigo: 'SG-LUVAS-00005-00',
    descricao: 'LUVA TIPO VAQUETA C/RASPA DE COURO CANO CURTO C.A',
    descricaoExtra: '17074',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Luvas de Proteção e Segurança',
    ca: '17074',
  },
  {
    codigo: 'SG-LUVAS-00006-00',
    descricao: 'LUVA ANTICORTE KRYTECH 586 TAM 9 CA 31346',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Luvas de Proteção e Segurança',
    fabricante: 'MAPA',
    ca: '31346',
  },
  {
    codigo: 'SG-LUVAS-00007-00',
    descricao: 'LUVA EM KEVLAR GRAFITEX 40CM FORRADA CA 29695',
    descricaoExtra: 'RES 250GRAUS',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Luvas de Proteção e Segurança',
    ca: '29695',
  },
  {
    codigo: 'SG-LUVAS-00008-00',
    descricao: 'LUVA SEG PU AZ 8 MAPA/KRYTECH586TAM8',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Luvas de Proteção e Segurança',
    fabricante: 'MAPA',
  },
  {
    codigo: 'SG-LUVAS-00009-00',
    descricao: 'LUVA DE SEG. VAQUETA CANO LONGO C.A.25387 20CM',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Luvas de Proteção e Segurança',
    ca: '25387',
  },
  {
    codigo: 'SG-LUVAS-00010-00',
    descricao: 'LUVA CONFEC. BORRACHA NITRILICA REVEST. INTER.',
    descricaoExtra: 'CA 25313',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Luvas de Proteção e Segurança',
    ca: '25313',
  },
  {
    codigo: 'SG-LUVAS-00011-00',
    descricao: 'LUVA SEG SS-CNIT 1007 CONTRA AG CORTE CA 32039 T8',
    descricaoExtra: 'AG ESCOTIANTE AG ABRASIVO',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Luvas de Proteção e Segurança',
    ca: '32039',
  },
  {
    codigo: 'SG-LUVAS-00012-00',
    descricao: 'LUVA PVC CANO LONGO E PALMA ASPERA C.A. 30514',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Luvas de Proteção e Segurança',
    ca: '30514',
  },
  {
    codigo: 'SG-LUVAS-00013-00',
    descricao: 'LUVA ANTI CORTE SS 1007 SUPER SAFETY C.A. 32039 T7',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Luvas de Proteção e Segurança',
    fabricante: 'SUPER SAFETY',
    ca: '32039',
  },
  {
    codigo: 'SG-MASCA-00001-00',
    descricao: 'MASCARA RESPIRADOR SEMI-FACIAL C/FILTRO QUIM C.A.',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Proteção Respiratória',
  },
  {
    codigo: 'SG-OCULO-00001-00',
    descricao: 'OCULOS SEG PC HAST ESPAT UNIC MSA/217729',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Óculos de Proteção e Facial',
    fabricante: 'MSA',
  },
  {
    codigo: 'SG-OCULO-00002-00',
    descricao: 'OCULOS SOBREPO ARMACAO E LENTE INCOLOR CA-18833/UV',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Óculos de Proteção e Facial',
    ca: '18833',
  },
  {
    codigo: 'SG-OCULO-00003-00',
    descricao: 'OCULOS SEG PC HAST ESPAT UNIC MSA/217663',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Óculos de Proteção e Facial',
    fabricante: 'MSA',
  },
  {
    codigo: 'SG-OCULO-00004-00',
    descricao: 'OCULOS SEG UVEX A700 INCOLOR HONEYWELL CA 18822',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Óculos de Proteção e Facial',
    fabricante: 'HONEYWELL',
    ca: '18822',
  },
  {
    codigo: 'SG-PROTE-00001-00',
    descricao: 'PROTETOR AURIC TP CONCH POMPMUFFLER0975',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Protetores Auriculares e Acessórios',
  },
  {
    codigo: 'SG-PROTE-00002-00',
    descricao: 'PROTETOR AURIC TP PLUG 3M/H0002312066 CA 5745',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Personal Protection Equipment',
    subcategoria: 'Protetores Auriculares e Acessórios',
    fabricante: '3M',
    ca: '5745',
  },
  {
    codigo: 'SG-PROTE-00003-00',
    descricao: 'PROTETOR DE BARBA PF BR C/100 UNIDADES - DEXCAR',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Disposable cloths',
    subcategoria: 'Descartáveis e Higiene',
    fabricante: 'DEXCAR',
  },
  {
    codigo: 'SG-PROTE-00005-00',
    descricao: 'PROTETOR FACIAL COM VISOR POLICARBONA INCOLOR CA',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Óculos de Proteção e Facial',
  },
  {
    codigo: 'SG-PROTE-00006-00',
    descricao: 'MASCARA PROTECAO DESCARTAVEL DUPLA TNT',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Disposable cloths',
    subcategoria: 'Proteção Respiratória e Descartáveis',
  },
  {
    codigo: 'SG-PROTE-00007-00',
    descricao: 'BONE SEG UNIC BIOPROT/CLASSICGOLDZLOGO CA 38352',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Capacetes, Bonés e Proteção da Cabeça',
    ca: '38352',
  },
  {
    codigo: 'SG-PROTE-00008-00',
    descricao: 'BONE SEG VM BIOPROT/CLASSICGOLDBA7CMVM',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Capacetes, Bonés e Proteção da Cabeça',
  },
  {
    codigo: 'SG-PROTE-00009-00',
    descricao: 'MANGOTE SEG GRAFITEX FIBRA ARAMIDA E ALGODAO T=UNI',
    descricaoExtra: 'C.A. 36841 COMPRIMENTO 50CM',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Mangotes e Proteção Corporal',
    ca: '36841',
  },
  {
    codigo: 'SG-PROTE-00010-00',
    descricao: 'MANGOTE THERM-K 003 TERMICO P/ ALTA TEMPERATURA',
    descricaoExtra: 'ATE 250IC BENETHERM C.A. 37904',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Mangotes e Proteção Corporal',
    fabricante: 'BENETHERM',
    ca: '37904',
  },
  {
    codigo: 'SG-PROTE-00011-00',
    descricao: 'BONE SEG CINZA ESCURO C/ CASQUET C.A38352 VISITANT',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Personal Protection Equipment',
    subcategoria: 'Capacetes, Bonés e Proteção da Cabeça',
    ca: '38352',
  },
  {
    codigo: 'SG-PROTE-00012-00',
    descricao: 'PROT AUDIT CONCH HASTE NUCA AI PT 21DB CA:43041',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Personal Protection Equipment',
    subcategoria: 'Protetores Auriculares e Acessórios',
    ca: '43041',
  },
  {
    codigo: 'SG-PROTE-00013-00',
    descricao: 'KIT HONEYWELL 1011998 HOWARD LEIGHT',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Personal Protection Equipment',
    subcategoria: 'Protetores Auriculares e Acessórios',
    fabricante: 'HONEYWELL HOWARD LEIGHT',
  },
  {
    codigo: 'SG-RESPI-00001-00',
    descricao: 'RESPIRADOR DESCART PO/NEV C/VALV 3M/PFF1',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Proteção Respiratória',
    fabricante: '3M',
  },
  {
    codigo: 'SG-SAPAT-00001-00',
    descricao: 'SAPATO SEG COUR ESTIVAL/WO10022S1PTNUM35',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
  },
  {
    codigo: 'SG-SAPAT-00002-00',
    descricao: 'SAPATO SEG COUR ESTIVAL/WO10022S1PTNUM36',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
  },
  {
    codigo: 'SG-SAPAT-00003-00',
    descricao: 'SAPATO SEG COUR ESTIVAL/WO10022S1PTNUM37',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
  },
  {
    codigo: 'SG-SAPAT-00004-00',
    descricao: 'SAPATO SEG COUR ESTIVAL/WO10022S1PTNUM38',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
  },
  {
    codigo: 'SG-SAPAT-00005-00',
    descricao: 'SAPATO C/BIQ ACO MOD.WO1002 N 39- C.A. 28142 ESTIV',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
    ca: '28142',
  },
  {
    codigo: 'SG-SAPAT-00006-00',
    descricao: 'SAPATO SEG COUR ESTIVAL/WO10022S1PTNUM40',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
  },
  {
    codigo: 'SG-SAPAT-00007-00',
    descricao: 'SAPATO SEG COUR ESTIVAL/WO10022S1PTNUM41',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
  },
  {
    codigo: 'SG-SAPAT-00008-00',
    descricao: 'SAPATO SEG COUR ESTIVAL/WO10022S1PTNUM42',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
  },
  {
    codigo: 'SG-SAPAT-00009-00',
    descricao: 'SAPATO SEG COUR ESTIVAL/WO10022S1PTNUM43',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
  },
  {
    codigo: 'SG-SAPAT-00010-00',
    descricao: 'SAPATO SEG COUR ESTIVAL/WO10022S1PTNUM44',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
  },
  {
    codigo: 'SG-SAPAT-00011-00',
    descricao: 'SAPATO SEG COUR ESTIVAL/WO10022S1PTNUM45',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Gloves, goggles, helmets, masks,...',
    subcategoria: 'Calçados de Segurança e Botas',
    fabricante: 'ESTIVAL',
  },
  {
    codigo: 'SG-TOUCA-00001-00',
    descricao: 'TOUCA DESCART NAO TECID C/ELAST BR UNIC',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Disposable cloths',
    subcategoria: 'Descartáveis e Higiene',
  },
  {
    codigo: 'SG-TOUCA-00002-00',
    descricao: 'TOUCA DESC TNT BRANCA GRANDE 70X54CM',
    descricaoExtra: '',
    materialSubGroup: 'Personal Protection Equipment',
    classification: 'Disposable cloths',
    subcategoria: 'Descartáveis e Higiene',
    dimensao: '70X54CM',
  },
];

console.log('Total Seguranca items in list:', RAW_SEGURANCA_92.length);

// Read current catalog
const catalogPath = path.join(__dirname, '../src/data/catalogItems.json');
const currentCatalog = JSON.parse(fs.readFileSync(catalogPath, 'utf8'));

// Filter out old SG items
const nonSgItems = currentCatalog.filter(
  (item) => !item.codigo.startsWith('SG-') && item.categoria !== 'MATERIAIS DE SEGURANÇA'
);

console.log('Non-SG items count:', nonSgItems.length);

function getKeywords(item) {
  const words = new Set();
  const text = `${item.codigo} ${item.descricao} ${item.descricaoExtra || ''} ${item.categoria} ${item.subcategoria} ${item.fabricante || ''} ${item.ca ? 'CA ' + item.ca : ''} ${item.classification || ''} ${item.materialSubGroup || ''} ${item.dimensao || ''}`;
  text
    .toLowerCase()
    .replace(/[^\w\sáàâãéèêíïóôõöúçñ-]/g, ' ')
    .split(/[\s,/\-_.]+/)
    .forEach((w) => {
      if (w.length >= 2) words.add(w);
    });
  return Array.from(words);
}

const formattedSgItems = RAW_SEGURANCA_92.map((raw) => {
  const subcode = raw.codigo.split('-')[1] || 'SEGUR';
  const obs = [];
  if (raw.descricaoExtra) obs.push(`Extra: ${raw.descricaoExtra}`);
  if (raw.ca) obs.push(`C.A.: ${raw.ca}`);
  if (raw.classification) obs.push(`Classificação: ${raw.classification}`);

  const itemObj = {
    id: `item-sg-${subcode.toLowerCase()}-${raw.codigo.split('-')[2]}`,
    codigo: raw.codigo,
    descricao: raw.descricao,
    categoria: 'MATERIAIS DE SEGURANÇA',
    subcategoria: raw.subcategoria,
    materialStructure: subcode,
    materialGroup: raw.materialSubGroup,
    fabricante: raw.fabricante || undefined,
    dimensao: raw.dimensao || undefined,
    localizacao: 'Almoxarifado Central - EPIs / Segurança',
    status: 'disponivel',
    favorito: false,
    documentos: [],
    observacoes: obs.length > 0 ? obs.join(' | ') : undefined,
    imagemUrl: '/assets/photos/botina-bracol.jpg',
  };

  itemObj.palavrasChave = getKeywords({
    ...itemObj,
    descricaoExtra: raw.descricaoExtra,
    classification: raw.classification,
    ca: raw.ca,
  });

  return itemObj;
});

const newCatalog = [...nonSgItems, ...formattedSgItems];
console.log('New Catalog Total Items:', newCatalog.length);

const cats = {};
newCatalog.forEach((i) => (cats[i.categoria] = (cats[i.categoria] || 0) + 1));
console.log('Categories breakdown:', cats);

fs.writeFileSync(catalogPath, JSON.stringify(newCatalog, null, 2), 'utf8');
console.log('Successfully updated catalogItems.json!');
